# Generated by Django 6.0.6 on 2026-06-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='authorities/profile/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='authorities/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Authority',
                'verbose_name_plural': 'Authorities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=15)),
                ('img', models.ImageField(upload_to='teachers/profile/')),
                ('documents', models.FileField(upload_to='teachers/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notice',
            name='desc',
            field=models.TextField(max_length=500),
        ),
    ]
