# Generated by Django 6.0.6 on 2026-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_authority_teacher_alter_notice_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
