# Generated by Django 6.0.6 on 2026-06-12 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_authority_is_active_teacher_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='student/')),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('adhaar_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must contain exactly 12 digits.', regex='^\\d{12}$')])),
                ('date_of_birth', models.DateField()),
                ('father_adhaar', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must contain exactly 12 digits.', regex='^\\d{12}$')])),
                ('father_voter', models.CharField(blank=True, max_length=100, null=True)),
                ('village', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('police_station', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must contain exactly 6 digits.', regex='^\\d{6}$')])),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('class_roll', models.CharField(max_length=10)),
                ('previous_class', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentclass')),
            ],
        ),
    ]
