# Generated by Django 6.0.6 on 2026-06-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=200)),
                ('b_img', models.ImageField(upload_to='books/')),
                ('author', models.CharField(max_length=300)),
                ('desc', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Library',
                'verbose_name_plural': 'Libraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MadrasahDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_img', models.ImageField(upload_to='mad_docu/')),
                ('desc', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Madrasah Document',
                'verbose_name_plural': 'Madrasah Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MadrasahInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_ests', models.IntegerField(default=1977)),
                ('m_about', models.TextField(max_length=1000)),
                ('m_course', models.TextField(max_length=1000)),
                ('m_vision', models.TextField(max_length=1000)),
                ('m_phone', models.CharField(max_length=13)),
                ('m_email', models.EmailField(default='soluamadrasahaofficial12@gmail.com', max_length=254)),
                ('m_logo', models.ImageField(upload_to='logo/')),
                ('m_name', models.CharField(default='Solua Madrasah Darul Quran', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('admission_message', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
