# Generated by Django 6.0.6 on 2026-06-21 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_library_madrasahdocuments_madrasahinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('period', models.PositiveIntegerField()),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='student.studentclass')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='student.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_class', 'period'), name='unique_class_period')],
            },
        ),
    ]
