# Generated by Django 6.0.6 on 2026-07-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student_admission_no_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(default='Islam', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(default='2026-27', max_length=9),
        ),
    ]
