# Generated by Django 6.0.6 on 2026-07-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_gender_student_religion_student_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_registered',
        ),
    ]
