# Generated by Django 6.0.6 on 2026-08-01 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_student_is_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='student.studentclass')),
            ],
        ),
        migrations.AlterField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='student.subject'),
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('HY', 'Half Yearly'), ('AN', 'Annual')], max_length=2)),
                ('full_mark', models.PositiveIntegerField(default=100)),
                ('pass_mark', models.PositiveIntegerField(default=33)),
                ('obtain_mark', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'subject', 'term'), name='unique_student_subject_term')],
            },
        ),
    ]
