# Generated by Django 6.0.6 on 2026-08-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_subject_alter_routine_subject_studentmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routines', to='student.studentclass'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='student.studentclass'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='student.studentclass'),
        ),
    ]
